# Generated by Django 6.0.2 on 2026-02-25 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_pedido_pedidoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitem',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='PedidoItem',
        ),
    ]
