# Generated by Django 6.0.2 on 2026-02-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_carrito_itemcarrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
    ]
